# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Biblio-LCC
version:      0.09
version_from: lib/Biblio/LCC.pm
installdirs:  site
requires:
    File::Basename:                0
    Getopt::Long:                  0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
